version: 2.1

commands:
  failed_job:
    steps:
      - run:
          name: Echo Failed Test
          command: echo circleci job- ${CIRCLE_JOB}  failed
          when: on_fail
        

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache: 
          key: "npm-package"
          paths: 
            - /src/node_modules
      - run: npm run lint
      - failed_job
          
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - "npm-package"
      - run: npm i
      - run: npm run test
      - failed_job

  analy:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - "npm-package"
      - run: npm run audit
      - failed_job

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analy:
          requires: 
            - build
