version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache: 
          key: "npm-package"
          paths: 
            - /src/node_modules
      - run: npm run lint
          
  # test:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache: 
  #         keys: 
  #           - "npm-package"
  #     - run: npm i
  #     - run: npm run test

  # analy:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache: 
  #         keys: 
  #           - "npm-package"
  #     - run: npm run audit

workflows:
  say-hello-workflow:
    jobs:
      - build
      # - test:
      #     requires: 
      #       - build
      # - analy:
      #     requires: 
      #       - build
