version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache: 
        key: "npm-package"
        paths: 
          - /src/node_modules
      - run: npm run lint
    test:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache: 
          key: 
            - "npm-package"
        - run: npm i
        - run: npm run test
    analyze:
        docker:
          - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache: 
        key: 
          - "npm-package"
      - run: npm audit

